MODEL:
  META_ARCHITECTURE: Baseline

  FREEZE_LAYERS: [ backbone ]

  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 50x
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    NORM: BN
    WITH_NL: False
    WITH_IBN: False
    PRETRAIN: False
    
  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    NECK_FEAT: after
    EMBEDDING_DIM: 0
    POOL_LAYER: gempool
    CLS_LAYER: circleSoftmax
    SCALE: 64
    MARGIN: 0.35

  LOSSES:
    NAME: ("CrossEntropyLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.
      
INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]

  DO_AUTOAUG: True
  AUTOAUG_PROB: 0.1

  REA:
    ENABLED: False
    PROB: 0.5

  CJ:
    ENABLED: True
    PROB: 0.5
    BRIGHTNESS: 0.15
    CONTRAST: 0.1
    SATURATION: 0.
    HUE: 0.

  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  FP16_ENABLED: True
  OPT: SGD
  SCHED: CosineAnnealingLR
  MAX_EPOCH: 40
  BASE_LR: 0.04
  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 256

  ETA_MIN_LR: 0.00004

  FREEZE_ITERS: 500

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 500

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 512

DATASETS:
  NAMES: ("CUHK03", "SAIVT", "AirportALERT", "iLIDS", "PKU", "PRAI", "SenseReID", "SYSU_mm", "Thermalworld", "PeS3D", "CAVIARa", "VIPeR", "Shinpuhkan", "WildTrackCrop", "cuhkSYSU", "LPW", "YouTube",)
  TESTS: ("DukeMTMC", "MSMT17", "Market1501","PartialREID", "PartialiLIDS", "OccludedREID", "CrowdREID",)
  COMBINEALL: True

CUDNN_BENCHMARK: True
